### ISSUE TITLE
Cannot find crawlers in list

### ISSUE THREAD

**Issue by ghost** [alephdata/memorious#124]
Hi,

Hope you are all well !

I tried to create a crawler, available at https://github.com/x0rzkov/memorious/tree/fmc/fmc. And, it cannot display the crawler fmc, neither, in the ui or the list from the cli.

Can you help me to point out what I missed configured ?

Thanks in advance for any insights or inputs on this issue.

Cheers,
X

**Comment by ghost** [comment]
Found the issue, you need to add MEMORIOUS_CONFIG_PATH env in the docker-compose.

Now, I have another issue. How to transfer crawled data to aleph ?

**Comment by ghost** [comment]
I have setup the following in the docker compose both for UI/workder service :
- ALEPH_HOST=http://xxx.xx.xxx.xx
- ALEPH_API_KEY=dfae7d3115734603812da2242xxxxxxx (from the profile section)

But I do not load data crawled by memorious to alpeh.

Can you help me to fix this last issue ? please.

**Comment by sunu** [comment]
Are you using the `aleph_emit` op to push data into Aleph?

**Comment by ghost** [comment]
Nope, I just though that setting up these 2 en variables gonna be enough.
How to use aleph_emit ?
