### ISSUE TITLE
fetch should ignore mailto links

### ISSUE THREAD

**Issue by rhiaro** [alephdata/memorious#128]
There's no case where we'd want to try to fetch mailto links is there? Would be handy to have fetch ignore these out of the box.

**Comment by pudo** [comment]
I guess we could even make this a whitelist instead: all we really understand is http, https and "nothing" (which probably implies Http) as the URL scheme.

**Comment by rhiaro** [comment]
makes sense - ftp and webdav are covered by other operations than fetch

**Comment by sunu** [comment]
Fixed in https://github.com/alephdata/memorious/commit/8965892c5ee685b0b9f3a38cb6c4bca4713536f5
