### ISSUE TITLE
Scheduled crawler don't run.

### ISSUE THREAD

**Issue by hsnamIT** [alephdata/memorious#142]
Hi guys,

I wrote a crawler and set the schedule setting to hourly but it doesn't run.

![Screenshot from 2020-10-11 13-15-48](https://user-images.githubusercontent.com/15093879/95671672-ee54df80-0bc3-11eb-91bf-ef091ab374ad.png)

The environment variable MEMORIOUS_SCHEDULER_INTERVAL=60 was set in the Dockerfile.

I searched back and forth for the solution but found nothing related to this error.

Could you tell me what I'm missing?

Thanks in advance

**Comment by sunu** [comment]
Memorious 2.0+ doesn't do crawler scheduling anymore.
