### ISSUE TITLE
Allow Xpath queries returning text, not just elements, in built-in parse function

### ISSUE THREAD

**Issue by Rinatius** [alephdata/memorious#43]
The problem probably lies in /memorious/memorious/operations/parse.py line 79 where text is being extracted from element, without check that it is actually an element.

**Comment by Rinatius** [comment]
So the problem is not with line 79 where it tries to get text content of the element, but with element = html.find(xpath) on line 76 it is capable apparently of returning only elements. element = html.xpath(xpath) would accept xpath returning actual text values for things like @src and @href.

**Comment by pudo** [comment]
Fixed.
