### ISSUE TITLE
Docker-compose example doesn't work

### ISSUE THREAD

**Issue by todorus** [alephdata/memorious#50]

**Comment by robinkiplangat** [comment]
Hi @todorus, 

I keep getting this error  with `docker-compose run ui` on example :
```
gunicorn.errors.HaltServer: <HaltServer 'App failed to load.' 4>
Failed to find application object 'app' in 'memorious.ui'
```
The crawler seems to works well on the command line, is there a workaround on this ?

**Comment by pudo** [comment]
hey @4bic this sounds like a bug that existed briefly a week ago or so. Let me try and do a fresh release, then we can check if it's gone there, ok?

**Comment by robinkiplangat** [comment]
Hi @pudo , Thank you for the heads up. I suppose I'll ping back when you do.

**Comment by pudo** [comment]
Try 0.9.0 once it is built. (which is now)

**Comment by robinkiplangat** [comment]
Hey @pudo, Great! works fine.
