### ISSUE TITLE
Load new crawlers without a restart

### ISSUE THREAD

**Issue by rhiaro** [alephdata/memorious#7]
If new crawlers are added to the CONFIG_PATH the celery workers can't see them without being turned off and on again.

Something about dynamic code reloading.

**Comment by pudo** [comment]
cf. https://docs.python.org/3.4/library/importlib.html#importlib.reload

**Comment by pudo** [comment]
Is this still relevant now that we have dev mode, which inlines all crawler execution and is based on many small invocations of the shell?

**Comment by rhiaro** [comment]
It'd still be nice to be able to add new production crawlers without restarting wouldn't it?

**Comment by pudo** [comment]
Yeah, but this raises a pretty weird question about live-updating docker containers in production, which I don't think we have a strong enough need for to figure out. My vote would be to close this for the moment.

**Comment by pudo** [comment]
OK, I don't think we'll come up with a fix for this. Closing unless we have an actual idea for how to wiggle it :)
