### ISSUE TITLE
`memorious run` command never finishes

### ISSUE THREAD

**Issue by alexmojaki** [alephdata/memorious#74]
I'm trying to automate the creation of new CSV files in opensanctions. When I run `memorious run us_ofac`, the last thing it does is store the data with a bunch of lines like this:

```
INFO:us_ofac.store:[us_ofac->store(balkhash_put)]: 2a24a44ca3e211e9a2fc0242ac160005
INFO:us_ofac.store:[us_ofac->store(balkhash_put)]: 2a24a44ca3e211e9a2fc0242ac160005
INFO:us_ofac.store:[us_ofac->store(balkhash_put)]: 2a24a44ca3e211e9a2fc0242ac160005
INFO:us_ofac.store:[us_ofac->store(balkhash_put)]: 2a24a44ca3e211e9a2fc0242ac160005
INFO:us_ofac.store:[us_ofac->store(balkhash_put)]: 2a24a44ca3e211e9a2fc0242ac160005
INFO:us_ofac.store:[us_ofac->store(balkhash_put)]: 2a24a44ca3e211e9a2fc0242ac160005
INFO:us_ofac.store:[us_ofac->store(balkhash_put)]: 2a24a44ca3e211e9a2fc0242ac160005
INFO:us_ofac.store:[us_ofac->store(balkhash_put)]: 2a24a44ca3e211e9a2fc0242ac160005
```

Then the command stays stuck open indefinitely. I'd like to write a shell script which performs other steps after this, but I don't see a good way to stop the command once it's finished and continue with the rest.

I don't want to use the memorious schedule or leave anything running all day. I want to briefly bring up the crawler once a day to scrape and produce files and then shut it down. It's also a problem in local development when testing changes to a crawler.

I've opened this here because it happens with all the opensanctions crawlers, so I'm assuming it's a core memorious problem. Does the command ever finish for other crawlers?

**Comment by sunu** [comment]
This should be fixed by https://github.com/alephdata/memorious/commit/d57d174366ac336b4bd0f4b77217bb45a96a032f

**Comment by sunu** [comment]
I'm closing this. Feel free to reopen if there's any issues.

**Comment by alexmojaki** [comment]
Thanks, this does work. Sorry it took me a while to check.
