### ISSUE TITLE
Frequent database deadlock errors

### ISSUE THREAD

**Issue by sunu** [alephdata/memorious#77]
We have a rate limit in place for db operations. But still under load, the db locks up sometimes throwing errors like:
```
(psycopg2.errors.DeadlockDetected) deadlock detected DETAIL: Process 974074 waits for ShareLock on transaction 2274650; blocked by process 974077. Process 974077 waits for ShareLock on transaction 2274652; blocked by process 974074.
```
These errors drown out other less frequent errors on the events screen.

**Comment by pudo** [comment]
There hasn't been a deadlock in more than a month, so I'm closing this because it may have been related to very specific crawlers going wild.
