### ISSUE TITLE
Installation instructions: /bin/bash absent from alpine

### ISSUE THREAD

**Issue by SylvainLapoix** [alephdata/memorious#78]
On an Ubuntu 18.04 server with last version of `memorious` installed.

I tried to run the command for the `worker` container [as specified in the installation documentation](https://memorious.readthedocs.io/en/latest/installation.html) but got this error

```
~/memorious/example$ docker-compose run --rm worker /bin/bash
Starting example_recognize-text_1 ... done
ERROR: Cannot start service worker: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"/bin/bash\": stat /bin/bash: no such file or directory": unknown`
```

## Solution

Going through documentation, I found [an issue on docker-library](https://github.com/docker-library/docs/issues/1437) that matched and tried this instead : 

`~/memorious/example$ docker-compose run --rm worker /bin/sh`

Worked fine !

**Comment by sunu** [comment]
Hi @SylvainLapoix, thanks for reporting this. It's fixed now :)

**Comment by SylvainLapoix** [comment]
Glad I helped, thank you for your reactivity !
