### ISSUE TITLE
Remove postgres dependency

### ISSUE THREAD

**Issue by rhiaro** [alephdata/memorious#8]
Make a version that has the option to run SQLite as the backend instead of Postgres

**Comment by pudo** [comment]
Find out what happens when you use 

http://docs.sqlalchemy.org/en/latest/core/type_basics.html#sqlalchemy.types.JSON 

on a SQLite DB.

**Comment by pudo** [comment]
https://avacariu.me/articles/2016/compiling-json-as-text-for-sqlite-with-sqlalchemy

**Comment by pudo** [comment]
This appears to be working fine.
