### ISSUE TITLE
normalize_url: False does not disable URL normalization

### ISSUE THREAD

**Issue by moreymat** [alephdata/memorious#87]
`memorious.logic.http` calls `normalizer.normalize_url` that drops query arguments with no value from URLs.
Specifying `normalize_url: False` in the YAML configuration file only prevents the first application of `normalize_url` in `ContextHttp.request()`, but does not prevent its second application in `ContextHttpResponse.url()`.
This breaks crawling on a number of websites.

**Comment by pudo** [comment]
Fixed now.
