### ISSUE TITLE
HelpWanted

### ISSUE THREAD

**Issue by nvelumani** [alephdata/memorious#89]
Hello Team,

I am trying to implement memorious, I had successfully downloaded, installed, ran the crawlers, I am able to see data under "/home/opensanctions/data/data/archive/ " but how do I access it, I don't see any documentation available for this purpose, if any document is available please direct me, It would be really helpful if I can get any help, Thanks in advance.  

Naveen.

**Comment by pudo** [comment]
For general help inquiries, please visit the Slack channel at: http://slack.alephdata.org. This bug tracker is intended for bug reports or other issues with the software. 

FWIW, check the documentation here: https://memorious.readthedocs.io/en/latest/buildingcrawler.html#storing
